### ISSUE TITLE
[Bug]: 大哥，你从我那借鉴仓库也就算了  不至于我备注里面bucket by 作者信息都改成自己的吧

### ISSUE THREAD

**Issue by arch3rPro** [whoopscs/scoop-security#3]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

aa

### Expected/Current Behaviour

aa

### Steps to Reproduce

```console
aa
```

### Possible Solution

aa

### Scoop and Buckets Version

```console
aa
```

### Scoop Config

```console
aa
```

### PowerShell Version

```console
aa
```

### Additional Softwares

大哥，你从我那借鉴仓库也就算了  不至于我备注里面bucket by 作者信息都改成自己的吧

**Comment by whoopscs** [comment]
不可否认，确实存在部分工具的描述和规则参考了您的仓库，未及时更新README文件的致谢信息引起误扰，至于bucket by的信息，在后面创建规则时也参考添加这个，并修改是考虑到在部分scoop仓库自动合并时保留信息。现已更新致谢信息，还请您见谅。
